### ISSUE TITLE
Internal Server Error on User Registration in Deployment

### ISSUE THREAD

**Issue by ChristopherJMiller** [realliance/senior-accounts#119]
Attempted to register a user on the deployed instance `https://accounts.senior.realliance.net`

Command Used: `curl -i -H "Content-Type: application/json" --request POST -d '{"email": "[REDACTED]", "username":"alumux","password":"[REDACTED]"}' https://accounts.senior.realliance.net/user`

**Expected** A Completed Response of either 200 or 400 (depending on whether I needed to adjust my command)

**Result** 500 Internal Server Error

This appears to be related to DB migrations in deployment?

**Comment by ConnorJC3** [comment]
Superseded by #131
